[tool.poetry]
name = "workouttracker"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Kivy = "^2.0.0"
tornado = "^6.1"
zipp = "^3.5.0"
HTMLParser = "^0.0.2"
lockfile = "^0.12.2"
Brotli = "^1.0.9"
importlib-metadata = "^4.8.1"
python-ntlm = "^1.1.0"
ordereddict = "^1.1"
toml = "^0.10.2"
cryptography = "^3.4.8"
Cython = "^0.29.24"
keyring = "^23.2.1"
lxml = "^4.6.3"
Pillow = "^8.3.2"
kivymd = "^0.104.2"
watchdog = "^2.1.5"
django-user = "^0.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
