<SettingsScreen>: 
    BoxLayout:
        oritentation: 'vertical'
        #size_hint:root.height,root.width
        MDToolbar:
            title: "Settings"
            font_name: 'assets/fonts/Inter-Medium.ttf'
            left_action_items: [["arrow-left", lambda x : app.go_to_home(x)]]
            md_bg_color: app.theme_cls.bg_light
            specific_text_color: (0,0,0,1)
            icon_color: (0,1,0,1)
            elevation: 0  
            
        MDBottomNavigation:
