<UserSettings>:
    BoxLayout:
        oritentation: 'vertical'
        MDToolbar:
                title: "User Settings"
                font_name: 'assets/fonts/Inter-Medium.ttf'
                left_action_items: [["arrow-left", lambda x : app.set_screen(x)]]
                md_bg_color: app.theme_cls.bg_light
                specific_text_color: (0,0,0,1)
                icon_color: (0,1,0,1)
                elevation: 0  
            
        MDBottomNavigation: