name: iOS Build
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

      # Runs a single command using the runners shell
      # export PATH=$PATH:~/.local/bin/ <- add this at the end?
      - name: Build iOS
        uses: ArtemSBulgakov/buildozer-action@v1
        run: | 
          brew install python pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer autoconf automake libtool openssl
          pip3 install --user --upgrade buildozer
          python3 -m pip install --user --upgrade pip virtualenv kivy-ios
          buildozer ios deploy run
            

      # Runs a set of commands using the runners shell
      # this command doesn't run: 'buildozer ios deploy run'
      # - name: Build for iOS
      #   run: |
      #     buildozer
