name: iOS Build
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path
        
      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}


      # Runs a single command using the runners shell
      # export PATH=$PATH:~/.local/bin/ <- add this at the end?
      # Creates an xcode project: python toolchain.py create ej
      - name: Build iOS
        id: buildozer
        run: | 
          brew install python pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer autoconf automake libtool openssl
          pip3 install --user --upgrade buildozer
          pip3 install --user --upgrade kivy-ios
          python3 -m pip install --user --upgrade pip virtualenv cython kivy-ios
          git clone https://github.com/kivy/kivy-ios.git
          cd kivy-ios/
          python3 -m venv venv
          . venv/bin/activate
          pip install -e .
          python toolchain.py build kivy pillow python3
          toolchain pip install kivymd
          toolchain create ExerciseJournal .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./kivy-ios

